[project]
name = "augsearch"
version = "0.0.1"

dependencies = [
    "beautifulsoup4 >= 4.13.3",
    "googlesearch-python >= 1.3.0",
    "ollama >= 0.4.7",
    "sentence-transformers >= 3.4.1" 

]

[project.scripts]
augsearch = "augsearch.run:main"